### PR TITLE
Fixed preventing to show duplicates

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
Initially I wanted to control which widget in the widget tree will show the overlay, but it turns out that the init order and especially `hashCode` is not deterministic and very unreliable.

This implementation does ensure that only one overlay is shown, but it looks a bit weird for `DropdownButton` items because the overlays will sometimes be in the popped up dropdown and sometimes where the selected item would be displayed (because there is a popup route that shows the selectable items that uses the same widgets as the widget that displays the current selection).

Please correct any mistakes.

### CODE REVIEW

**Comment by axel-op** [comment]
> This implementation does ensure that only one overlay is shown, but it looks a bit weird for DropdownButton items because the overlays will sometimes be in the popped up dropdown and sometimes where the selected item would be displayed (because there is a popup route that shows the selectable items that uses the same widgets as the widget that displays the current selection).

Not sure I understood that part 🤔

**Comment by creativecreatorormaybenot** [comment]
@axel-op So what `DropdownButton` does is it uses an `IndexedStack` in the route you have the dropdown button in to display the selected item.

Now if you tap it, it will show a `PopupRoute` with all the items you can select, but these items are the **same widgets** as the ones in the `IndexedStack`.

So what I am trying to do is display feature discovery on the opened `DropdownButton`, but this has the effect of having every widget in the widget tree twice, once in the `IndexedStack` in "my" route and once in the `PopupRoute`.
Now, when I run `discoverFeatures` with the solution in this PR, the overlay is shown seemingly at random either centered about the widget in the `IndexedStack` or in the `PopupRoute`.

Wanna merge this or try to implement the version that shows the overlay about the most recent widget?

**Comment by creativecreatorormaybenot** [comment]
Btw, tests would be great, but if you want to add them, you might just want to revert my changes and test them first before adding them back.

**Comment by creativecreatorormaybenot** [comment]
And about the repositioning thing: I was wrong, it does get adjusted when rotating, it is just that the position seems really off in landscape. (and we are in the same time zone, which is why my changes are so poor)

**Comment by axel-op** [comment]
I think that this would put too much responsibility on this widget. I don't think it has to handle that, as users can choose when to display them ; why prevent them to display multiple FeatureDiscovery if they want to?

**Comment by creativecreatorormaybenot** [comment]
@axel-op You can make it an optional parameter if you want to, but users of `DropdownButton` do not have a choice because it does not let you specify what widgets it uses in the `PopupRoute`, it just automatically uses the same ones. `Hero` e.g. is more forgiving, it has a `shuttleBuilder`, but not everyone uses that.  
Meaning, I don't have a choice but to put it in here. I can have my own fork if you like, but I thought it might help others.  
I might try to display only the most recent widget properly and make that optional, but this solution works fine for now.

> why prevent them to display multiple FeatureDiscovery if they want to?

That does not work currently either. The only thing that happens is multiple on top of each other, which cover the contents, just looks ugly.

**Pull request merged**
