### PR TITLE
Fix discoverFeatures after dismissal

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
I am sorry about this one.

### CODE REVIEW

**Comment by axel-op** [comment]
This fixes the problem.
However when one overlay is dismissed the next ones aren't shown either (that is, the process of showing the different steps is stopped). Is this a behavior we want?

**Comment by creativecreatorormaybenot** [comment]
@axel-op Yes, this is the point of dismissal. If you want to continue, you need to tap the tap target.

I saw that the Android Google Translate app used feature discovery where they would add a clickable text to continue as well, so they had two options: tap target or text. (text was "Understood")

**Comment by creativecreatorormaybenot** [comment]
@axel-op See https://material.io/archive/guidelines/growth-communications/feature-discovery.html#feature-discovery-volume-frequency, however, I would be oppen to expanding upon that to match what I saw in Google Translate, i.e. leave the original spec a bit, or not even leave it, just follow the guidelines, like the one I linked and interpret what that could mean.

**Comment by axel-op** [comment]
You're right, that's in the spec! I didn't remember seeing this. 
What did you see in GTranslate?

**Comment by creativecreatorormaybenot** [comment]
@axel-op Mentioned it before you merged the PR.

> I saw that the Android Google Translate app used feature discovery where they would add a clickable text to continue as well, so they had two options: tap target or text. (text was "Understood")

**Comment by axel-op** [comment]
I missed it. But I don't get it

**Comment by creativecreatorormaybenot** [comment]
I will do my best to demonstrate it with Paint (cannot recreate it because it only showed after an update, "this is a new feature"):

**Comment by axel-op** [comment]
Ok now I see!
This reminds me that you didn't mark the methods in `FeatureDiscovery` class as private (or maybe it was like that before?).
So I think that instead of implementing that, we should transform the `description` parameter so it would accept any widget. Therefore, users could pass a button that calls the `dismiss` method of `FeatureDiscovery` in this widget.

**Comment by creativecreatorormaybenot** [comment]
Not sure if I added any methods, could you link wich ones you mean?

Passing widgets sounds reasonable, however, having to layout them can be rather challenging. I think that it is good that the package handles this, but an optional button like this seems reasonable to me.

**Comment by axel-op** [comment]
> Not sure if I added any methods, could you link wich ones you mean?

The four methods in the `FeatureDiscovery` class: `markStepComplete`, `activeStep`, `discoverFeatures` and `dismiss`. Users can call them at anytime! (And we should probably restrict access to some of them.)

> Passing widgets sounds reasonable, however, having to layout them can be rather challenging. I think that it is good that the package handles this, but an optional button like this seems reasonable to me.

I'm sure this wouldn't be that big of a deal. Users would test the rendering anyway. Plus, did you know that for now, length of text passed in `title` and in `description` is not controlled, and if it is too long it exceeds the circle circumference?

**Comment by creativecreatorormaybenot** [comment]
> Plus, did you know that for now, length of text passed in title and in description is not controlled, and if it is too long it exceeds the circle circumference?

I guess vertically, but at least it is constrained horizontally. I just think that it is easier to use if you do not have to provide widgets for these clearly defined features.  
Maybe both would be good? (`Text(text) ?? textWidget`)

I mean you do not interact with the text, so there is less need for a widget, but widgets are always nice for keys, semantics, etc.

> The four methods in the FeatureDiscovery class: markStepComplete, activeStep, discoverFeatures and dismiss. Users can call them at anytime! (And we should probably restrict access to some of them.)

I did not change that, but I do not care too much. It is probably better design to make everything that should not be used private, but if someone wants to call it, why not. E.g. I rely on `activeStep` to implement back button behavior on Android in my app.  
Edit: actually, all of these four are the public facing methods and they are made to be public (I think). The user probably wants the ability to programmatically dismiss and get status on the discovery steps.

**Comment by axel-op** [comment]
I think we should do as you did with the icon: to let the user pass any widget they want. 
And we could totally constrain it horizontally as well.

**Comment by creativecreatorormaybenot** [comment]
Yep, sounds good. We could even add a theme about the text to stylize any passed `Text` widget in the package automatically if we want. If you were to add that, I would be totally open to review it. I think I will be fine without it for now, but having another slot for a button like the one Google Translate has would be good, i.e. `title` , `description`, and `action` slots.

**Comment by axel-op** [comment]
> Yep, sounds good. We could even add a theme about the text to stylize any passed Text widget in the package automatically if we want. 

That's actually what I was going to do 😄

> I think I will be fine without it for now, but having another slot for a button like the one Google Translate has would be good, i.e. title , description, and action slots.

Again, users could pass a widget in `description` that directly calls the `dismiss` method. To me there is no need to complexify our already complex widget, furthermore it's not as if we had to constrain the button theme.

**Comment by creativecreatorormaybenot** [comment]
> Again, users could pass a widget in description that directly calls the dismiss method. To me there is no need to complexify our already complex widget, furthermore it's not as if we had to constrain the button theme.

That would be the `markStepComplete` method probably, but what I was actually going for is having a distinct location and style for the action that is somewhat the same accross apps, but you are right, passing a `Column` (containing the description and the action) with `Padding` for the action is fine as well.

**Comment by axel-op** [comment]
> Yep, sounds good. We could even add a theme about the text to stylize any passed Text widget in the package automatically if we want. If you were to add that, I would be totally open to review it. I think I will be fine without it for now, but having another slot for a button like the one Google Translate has would be good, i.e. title , description, and action slots.

Done in #13. Let me know what you think! (also, take a look at the example 😊)

**Pull request merged**
