### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by axel-op**

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
👍

**Comment by axel-op** [comment]
😅 What I actually want to do is to extract the scores of the package from the `pana` output and to automatically add a comment with them in the PR. 
But to do this I should:
1. save the output from one step to use it in the next one;
2. parse this JSON output and extract the scores;
3. publish the comment.

I probably better create my own action at this point, but in order to do so I should first learn Javascript...

**Comment by axel-op** [comment]
😅 What I actually want to do is to extract the scores of the package from the `pana` output and to automatically add a comment with them in the PR. 
But to do this I must:
1. save the output from one step to use it in the next one;
2. parse this JSON output and extract the scores;
3. publish the comment.

I probably better create my own action at this point, but in order to do so I should first learn Javascript... 

Anyway

**Comment by creativecreatorormaybenot** [comment]
@axel-op Do you not want to merge this for now?

**Comment by axel-op** [comment]
> @axel-op Do you not want to merge this for now?

Not for now, no. 

EDIT: Well actually I'm not ready to work on this anytime soon so...

**Comment by creativecreatorormaybenot** [comment]
Can we delete old branches?

**Comment by axel-op** [comment]
> Can we delete old branches?

It's done for the others but I'm keeping this one for now

**Pull request merged**
