### PR TITLE
Stream implementation instead of InheritedWidget

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**

### CODE REVIEW

**Comment by creativecreatorormaybenot** [comment]
Just like this the comments are a lot clearer and the tests can even be run 👍

**Comment by axel-op** [comment]
https://github.com/axel-op/feature_discovery/pull/18#issuecomment-532624010
> @axel-op But this is worse because it will not complete the step if the DescribedFeatureOverlay was not listening at the time the event was dispatched, right?
> Meaning that the overlay could be out of sync with the state of the current feature discovery.
> I guess in that case we would need a BehaviorSubject, but that is totally up to you because as I mentioned before, I would just not do it because the current implementation works great (the stream one works great as well).

I don't understand: the widgets subscribe to the streams as soon as they're initialized, so this will never happen? 

Also please note that my last commit fixed a bug and now all tests pass.

**Comment by creativecreatorormaybenot** [comment]
>I don't understand: the widgets subscribe to the streams as soon as they're initialized, so this will never happen?

The point I was trying to make is that the "issue" I described in https://github.com/axel-op/feature_discovery/pull/18#pullrequestreview-288366056 will only occur when there is no `DescribedFeatureOverlay`, but when it appears just after some time, it will still work fine. However, if the `DescribedFeatureOverlay` is missing at the beginning with the stream implementation, it will just break and not work if it shows up later because the events were dispatched before the widget subscribed to the streams. This is what I liked about the `InheritedWidget` implementation: it does not rely on any `DescribedFeatureOverlay` to be active initially and does not need to "connect" to them. It just works because of the dependency logic. 

But seriously it's just w/e. I really do not have any issue with any of the two implementations.

**Comment by axel-op** [comment]
@creativecreatorormaybenot Do you have in mind a situation where, for example, a `DescribedFeatureOverlay` would be in a new route that is pushed after calling the `discoverFeatures` method?

But even in that case, the new widget will be able to retrieve the Bloc and its streams. So I don't get it when you say 
> However, if the DescribedFeatureOverlay is missing at the beginning with the stream implementation, it will just break and not work if it shows up later because the events were dispatched before the widget subscribed to the streams.

**Comment by creativecreatorormaybenot** [comment]
@axel-op If it listens to the stream it won't get any events that were sent before it started listening, right?

**Comment by axel-op** [comment]
Right, and in which case this would be a problem?

**Comment by creativecreatorormaybenot** [comment]
@axel-op I said it's w/e, but it's the same for the `InheritedWidget` implementation.

**Comment by axel-op** [comment]
@creativecreatorormaybenot I have made a PR on the original repo. 
I think I'm done with this package for now! It was nice working with you on it :)

**Comment by creativecreatorormaybenot** [comment]
@axel-op So why did you switch to streams, I am confused now because you did not change anything other than that, right?

Likewise

**Comment by axel-op** [comment]
@creativecreatorormaybenot Actually the body of the deprecated functions have been edited and they now only call the new functions, that work thanks to my new implementation. 

Also see https://github.com/ayalma/feature_discovery/pull/3.

**Pull request merged**
