### PR TITLE
Fix example

### LINKED ISSUE #29: featureId != null is not true
I wanted to test your implementation as it you have finished it now, but starting the example and trying to dismiss or complete the "Find the fastest route" step does not work.  
The example app is completely bricked for me, no matter what I try to do.

Apparently, `_activeStepId` is `null`. I wanted to create this issue first before debugging as you might know why this is happening.

### PR DESCRIPTION
**Pull request by axel-op**
This resolves #29

### CODE REVIEW

**Review by creativecreatorormaybenot — CHANGES_REQUESTED** [review]
https://github.com/axel-op/feature_discovery/issues/29#issuecomment-534773350

The failing assertion is at `described_feature_overlay.dart:168:14`. I ran it using the latest code from the `example-fix` branch. (`git pull`, `git checkout example-fix`)

**Comment by axel-op** [comment]
Alright so I just learnt about [this package](https://pub.dev/packages/provider) that should solve many problems related to #29 (that is, data persistence and access to the bloc). 
Using this package, the bloc now shouldn't be rebuilt with its parent, and this save us from using an InheritedWidget or even a StatefulWidget as I did. 

Also I moved the bloc in another file for readability. 

Finally I added the `const` keyword to the constructor of `FeatureDiscovery`, now that the bloc isn't created in this constructor anymore.

**Comment by creativecreatorormaybenot** [comment]
I dislike this because it adds weight. I'd rather revert to the old system.

**Comment by axel-op** [comment]
@creativecreatorormaybenot Really? I don't think it adds that much weight… It's a very useful package that I think has been recently published, and it will probably be used by a lot of users in their own project anyways… 

You can revert to the previous implementation, but don't forget #21

**Comment by creativecreatorormaybenot** [comment]
@axel-op Actually, never mind what I said. I really want to fix #34 and #33, but I think that I will just transfer them to https://github.com/ayalma/feature_discovery, which allows you to further improve the core of the package here. Later, we can ideally merge the two or I can merge the branch from my fork into your fork.  
The reasoning behind this is that these core improvements are not needed for #34 and #33.

**Comment by axel-op** [comment]
@creativecreatorormaybenot So what do you wanna do?..

**Review by creativecreatorormaybenot — APPROVED** [review]
Changes are fine, #29 persists for me.

**Pull request merged**
